import DashboardCard from "../common/DashboardCard";

export default function RecommendationCard({
  recommendations = [],
  search = "",
}) {
  const filtered = recommendations.filter((item) =>
    item.toLowerCase().includes(search.toLowerCase()),
  );

  return (
    <DashboardCard
      title="Founder Recommendations"
      subtitle="Strategic insights generated by your AI COO"
    >
      <div className="space-y-4">
        {filtered.length ? (
          filtered.map((item, index) => (
            <div
              key={index}
              className="rounded-xl border border-slate-200 bg-slate-50 p-5"
            >
              <div className="flex gap-4">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-indigo-600 text-white font-bold">
                  {index + 1}
                </div>

                <p>{item}</p>
              </div>
            </div>
          ))
        ) : (
          <p className="text-slate-500">No recommendations found.</p>
        )}
      </div>
    </DashboardCard>
  );
}
